all: bitoperations cmdargs func2 preproc sha256

bitoperations: bit-operations.c
	gcc -o bitoperations bit-operations.c

cmdargs: cmdargs.c
	gcc -o cmdargs cmdargs.c

func2: func2.c
	gcc -o func2 func2.c

preproc: preproc.c
	gcc -o preproc preproc.c

sha256: sha256.c
	gcc -o sha256 sha256.c